// <auto-generated />
using System;
using ApiCovid.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCovid.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCovid.Domain.Models.Relatorio", b =>
                {
                    b.Property<Guid>("IdRelatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("IdSolicitante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QtdeVacinados")
                        .HasColumnType("int");

                    b.Property<DateTime>("RJ_Datadaaplicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("IdRelatorio");

                    b.HasIndex("IdSolicitante");

                    b.ToTable("Relatorio");
                });

            modelBuilder.Entity("ApiCovid.Domain.Models.Solicitante", b =>
                {
                    b.Property<Guid>("IdSolicitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Perfil")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.HasKey("IdSolicitante");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Solicitante");
                });

            modelBuilder.Entity("ApiCovid.Domain.Models.Relatorio", b =>
                {
                    b.HasOne("ApiCovid.Domain.Models.Solicitante", "Solicitante")
                        .WithMany("Relatorios")
                        .HasForeignKey("IdSolicitante")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("ApiCovid.Domain.Models.Solicitante", b =>
                {
                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
